### ISSUE TITLE
Android App Distribution

### ISSUE THREAD

**Issue by JamesKPreston** [JamesKPreston/movie_date#37]
We need to create some secrets. Go to your repository settings and add the following secrets:

- STORE_PASSWORD: The password for your keystore file.
- KEY_JKS: The base64 encoded keystore file.
- SEC_JSON: The base64 encoded service account JSON file.
- FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: The app-specific password for your Apple developer account.

To encode the files, you can use the following command:

`cat path/to/your/file | openssl base64`

  ```
build_android:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-android
      cancel-in-progress: true
    name: Build and Deploy Android
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3.3.0
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Create Key properties file
        run: |
            cat << EOF > "./android/key.properties"
            storePassword=${{ secrets.STORE_PASSWORD }} 
            keyPassword=${{ secrets.STORE_PASSWORD }}
            keyAlias=upload
            storeFile=./key.jks
            EOF            
      - name: Decode key file
        run: echo "${{ secrets.KEY_JKS }}" | openssl base64 -d -out ./android/app/key.jks
      - name: Decode sec json file
        run: echo "${{ secrets.SEC_JSON }}" | openssl base64 -d -out ./android/sec.json
      - uses: subosito/flutter-action@v2
      - run: flutter packages pub get
      - run: flutter build appbundle --release
      - name: Fastlane Action
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: deploy
          subdirectory: android
```
